require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Product = require('../models/Product');

// This is your complete, validated product list
const products = [
  // Mobiles (11)
  { name: 'Apple iPhone 15 Pro', slug: 'apple-iphone-15-pro-256gb', description: 'Titanium design, A17 Pro chip, pro camera system with 5x telephoto.', price: 134900, category: 'Mobiles', brand: 'Apple', imageUrls: ['/images/mobiles/apple-iphone-15-pro.jpg'], stock: 25, keyFeatures: ['A17 Pro chip', '6.1-inch Super Retina XDR', 'USB-C', '5G', 'Titanium build'], variants: [{ type: 'Storage', value: '256GB', price: 134900 }, { type: 'Storage', value: '512GB', price: 149900 }] },
  { name: 'Apple iPhone 14', slug: 'apple-iphone-14-128gb', description: 'All-day battery, powerful A15 Bionic, and advanced dual‑camera system.', price: 69999, category: 'Mobiles', brand: 'Apple', imageUrls: ['/images/mobiles/iphone-14.jpg'], stock: 40, keyFeatures: ['A15 Bionic', '6.1-inch display', 'Crash Detection', 'Ceramic Shield'], variants: [{ type: 'Storage', value: '128GB', price: 69999 }, { type: 'Storage', value: '256GB', price: 76999 }] },
  { name: 'Samsung Galaxy S25', slug: 'samsung-galaxy-s25-256gb', description: 'Dynamic AMOLED 2X with 120Hz, pro-grade camera, Galaxy AI features.', price: 74999, category: 'Mobiles', brand: 'Samsung', imageUrls: ['/images/mobiles/galaxy-s25.jpg'], stock: 45, keyFeatures: ['Snapdragon 8 Elite', '50MP triple camera', 'IP68', 'One UI'], variants: [{ type: 'Storage', value: '256GB', price: 74999 }] },
  { name: 'Samsung Galaxy Z Fold5', slug: 'samsung-galaxy-z-fold5-256gb', description: 'Foldable display, multitasking powerhouse with S Pen support.', price: 154999, category: 'Mobiles', brand: 'Samsung', imageUrls: ['/images/mobiles/galaxy-fold.jpg'], stock: 20, keyFeatures: ['7.6-inch foldable', 'S Pen support', 'Advanced multitasking'], variants: [{ type: 'Storage', value: '256GB', price: 154999 }] },
  { name: 'OnePlus 13 5G', slug: 'oneplus-13-5g-256gb', description: 'Sleek flagship with ProXDR display and Hasselblad-tuned cameras.', price: 54999, category: 'Mobiles', brand: 'OnePlus', imageUrls: ['/images/mobiles/oneplus-13.jpg'], stock: 60, keyFeatures: ['120Hz LTPO', 'Snapdragon flagship', '80W SUPERVOOC'], variants: [{ type: 'Storage', value: '256GB', price: 54999 }, { type: 'Storage', value: '512GB', price: 59999 }] },
  { name: 'OnePlus Open', slug: 'oneplus-open-512gb', description: 'Ultra-thin foldable with dual 2K 120Hz ProXDR displays.', price: 139999, category: 'Mobiles', brand: 'OnePlus', imageUrls: ['/images/mobiles/oneplus-open.jpg'], stock: 30, keyFeatures: ['Dual 2K 120Hz', 'Hasselblad camera', 'Lightweight design'], variants: [{ type: 'Storage', value: '512GB', price: 139999 }] },
  { name: 'Vivo V29 Pro', slug: 'vivo-v29-pro-256gb', description: 'Smart Aura Light Portrait with 50MP Eye AF selfie camera.', price: 39999, category: 'Mobiles', brand: 'Vivo', imageUrls: ['/images/mobiles/vivo-v29.jpg'], stock: 80, keyFeatures: ['Aura Light Portrait', '3D curved display', '5G'], variants: [{ type: 'Storage', value: '256GB', price: 39999 }] },
  { name: 'Vivo X100', slug: 'vivo-x100-256gb', description: 'Flagship imaging system with Zeiss optics and premium performance.', price: 62999, category: 'Mobiles', brand: 'Vivo', imageUrls: ['/images/mobiles/vivo-x100.jpg'], stock: 35, keyFeatures: ['Zeiss optics', 'AMOLED 120Hz', 'Fast charging'], variants: [{ type: 'Storage', value: '256GB', price: 62999 }] },
  { name: 'Xiaomi 13 Pro', slug: 'xiaomi-13-pro-256gb', description: 'Leica professional optics with 1-inch sensor and 120W HyperCharge.', price: 69999, category: 'Mobiles', brand: 'Xiaomi', imageUrls: ['/images/mobiles/xiaomi-13-pro.jpg'], stock: 25, keyFeatures: ['Leica camera', '120W charging', 'AMOLED 120Hz'], variants: [{ type: 'Storage', value: '256GB', price: 69999 }] },
  { name: 'Xiaomi Redmi Note 13 Pro', slug: 'xiaomi-redmi-note-13-pro-256gb', description: 'Value flagship with sharp display and long battery life.', price: 26999, category: 'Mobiles', brand: 'Xiaomi', imageUrls: ['/images/mobiles/redmi-note-13.jpg'], stock: 120, keyFeatures: ['120Hz AMOLED', '108MP camera', '67W fast charge'], variants: [{ type: 'Storage', value: '256GB', price: 26999 }] },
  { name: 'Apple iPhone 16 Air', slug: 'apple-iphone-16-air-256gb', description: 'A19 performance, advanced dual camera, and Apple Intelligence features.', price: 119900, category: 'Mobiles', brand: 'Apple', imageUrls: ['/images/mobiles/apple-iphone-16.jpg'], stock: 30, keyFeatures: ['6.3-inch 120Hz', 'A19 chip', 'IP68'], variants: [{ type: 'Storage', value: '256GB', price: 119900 }, { type: 'Storage', value: '512GB', price: 129900 }] },

  // Laptops (11)
  { name: 'Apple MacBook Air 13 M4', slug: 'apple-macbook-air-13-m4', description: 'Ultra-light notebook with Apple M4 and Liquid Retina display.', price: 93990, category: 'Laptops', brand: 'Apple', imageUrls: ['/images/laptops/macbook-air.jpg'], stock: 35, keyFeatures: ['Apple M4', '13.6-inch Liquid Retina', 'All-day battery'], variants: [{ type: 'RAM', value: '16GB', price: 93990 }, { type: 'SSD', value: '512GB', price: 108990 }] },
  { name: 'Apple MacBook Pro 14 M3', slug: 'apple-macbook-pro-14-m3', description: 'Pro performance with M3 and exceptional battery life.', price: 169990, category: 'Laptops', brand: 'Apple', imageUrls: ['/images/laptops/macbook-pro.jpg'], stock: 20, keyFeatures: ['Apple M3', '14-inch Liquid Retina XDR', 'Pro apps ready'], variants: [{ type: 'SSD', value: '512GB', price: 169990 }] },
  { name: 'Dell Inspiron 14', slug: 'dell-inspiron-14', description: 'Everyday productivity laptop with 12th Gen Intel Core i5.', price: 58990, category: 'Laptops', brand: 'Dell', imageUrls: ['/images/laptops/dell-inspiron.jpg'], stock: 50, keyFeatures: ['Intel Core i5', '14-inch FHD', 'Backlit keyboard'], variants: [{ type: 'RAM', value: '16GB', price: 58990 }] },
  { name: 'Dell XPS 13', slug: 'dell-xps-13', description: 'Premium ultrabook with edge-to-edge display and solid build.', price: 149990, category: 'Laptops', brand: 'Dell', imageUrls: ['/images/laptops/dell-xps.jpg'], stock: 15, keyFeatures: ['Intel Core i7', '13.4-inch OLED', 'Thunderbolt 4'], variants: [{ type: 'SSD', value: '1TB', price: 149990 }] },
  { name: 'Lenovo IdeaPad Slim 5', slug: 'lenovo-ideapad-slim-5', description: 'Slim and light with AMD Ryzen 7 and fast SSD storage.', price: 62990, category: 'Laptops', brand: 'Lenovo', imageUrls: ['/images/laptops/lenovo-ideapad.jpg'], stock: 45, keyFeatures: ['Ryzen 7', '16GB RAM', '512GB SSD'], variants: [{ type: 'RAM', value: '16GB', price: 62990 }] },
  { name: 'Lenovo Legion 5', slug: 'lenovo-legion-5', description: 'Gaming laptop with RTX 4060 and Legion Coldfront cooling.', price: 129990, category: 'Laptops', brand: 'Lenovo', imageUrls: ['/images/laptops/lenovo-legion.jpg'], stock: 18, keyFeatures: ['RTX 4060', '165Hz display', 'RGB keyboard'], variants: [{ type: 'SSD', value: '1TB', price: 129990 }] },
  { name: 'HP Pavilion 15', slug: 'hp-pavilion-15', description: 'Reliable all-rounder with Intel Core i5 and micro-edge display.', price: 57990, category: 'Laptops', brand: 'HP', imageUrls: ['/images/laptops/hp-pavilion.jpg'], stock: 55, keyFeatures: ['Intel Core i5', '15.6-inch FHD', 'Fast charge'], variants: [{ type: 'RAM', value: '16GB', price: 57990 }] },
  { name: 'HP Omen 16', slug: 'hp-omen-16', description: 'Performance gaming laptop with RTX 4070 graphics.', price: 149990, category: 'Laptops', brand: 'HP', imageUrls: ['/images/laptops/hp-omen.jpg'], stock: 20, keyFeatures: ['RTX 4070', '165Hz QHD', 'OMEN Tempest cooling'], variants: [{ type: 'SSD', value: '1TB', price: 149990 }] },
  { name: 'Samsung Galaxy Book3', slug: 'samsung-galaxy-book3', description: 'Thin and light with AMOLED display and seamless Galaxy ecosystem.', price: 94990, category: 'Laptops', brand: 'Samsung', imageUrls: ['/images/laptops/galaxy-book3.jpg'], stock: 28, keyFeatures: ['AMOLED display', 'Intel Core i7', 'Fast charge'], variants: [{ type: 'SSD', value: '512GB', price: 94990 }] },
  { name: 'Samsung Galaxy Book4 Pro', slug: 'samsung-galaxy-book4-pro', description: 'Dynamic AMOLED 2X touchscreen and powerful Intel Core Ultra processor.', price: 159990, category: 'Laptops', brand: 'Samsung', imageUrls: ['/images/laptops/galaxy-book4.jpg'], stock: 12, keyFeatures: ['AMOLED', '2-in-1', 'S Pen'], variants: [{ type: 'SSD', value: '1TB', price: 139990 }] },
  { name: 'HP Envy x360', slug: 'hp-envy-x360', description: 'Stylish 2-in-1 OLED with fast performance.', price: 99990, category: 'Laptops', brand: 'HP', imageUrls: ['/images/laptops/hp-envy.jpg'], stock: 26, keyFeatures: ['OLED display', '2-in-1', 'Backlit keyboard'], variants: [{ type: 'SSD', value: '1TB', price: 99990 }] },

  // Televisions (11)
  { name: 'Samsung 55-inch Crystal 4K', slug: 'samsung-55-crystal-4k', description: 'PurColor for a vibrant picture and Crystal Processor 4K.', price: 45990, category: 'Televisions', brand: 'Samsung', imageUrls: ['/images/tvs/samsung-crystal.jpg'], stock: 30, keyFeatures: ['Crystal Processor 4K', 'HDR', 'Q-Symphony'], variants: [] },
  { name: 'Samsung 65-inch Neo QLED 8K', slug: 'samsung-65-neo-qled-8k', description: 'Breathtaking 8K detail with AI upscaling.', price: 289990, category: 'Televisions', brand: 'Samsung', imageUrls: ['/images/tvs/samsung-neo-qled.jpg'], stock: 8, keyFeatures: ['8K', 'Neo QLED', 'Dolby Atmos'], variants: [] },
  { name: 'LG 55-inch OLED evo', slug: 'lg-55-oled-evo', description: 'Perfect blacks and AI Picture Pro for stunning detail.', price: 129990, category: 'Televisions', brand: 'LG', imageUrls: ['/images/tvs/lg-oled.jpg'], stock: 15, keyFeatures: ['OLED evo', '4K', 'Dolby Vision IQ'], variants: [] },
  { name: 'LG 75-inch NanoCell', slug: 'lg-75-nanocell', description: 'Big screen 4K with NanoColor and local dimming.', price: 149990, category: 'Televisions', brand: 'LG', imageUrls: ['/images/tvs/lg-nanocell.jpg'], stock: 10, keyFeatures: ['NanoCell', '4K', 'Filmmaker Mode'], variants: [] },
  { name: 'Sony Bravia 65-inch XR', slug: 'sony-bravia-65-xr', description: 'Cognitive Processor XR delivers lifelike picture and sound.', price: 219990, category: 'Televisions', brand: 'Sony', imageUrls: ['/images/tvs/sony-bravia-xr.jpg'], stock: 9, keyFeatures: ['Cognitive XR', '4K HDR', 'Acoustic Multi-Audio'], variants: [] },
  { name: 'Sony Bravia 55-inch LED', slug: 'sony-bravia-55-led', description: '4K HDR with Motionflow XR and rich colors.', price: 79990, category: 'Televisions', brand: 'Sony', imageUrls: ['/images/tvs/sony-bravia-led.jpg'], stock: 18, keyFeatures: ['4K HDR', 'Motionflow XR', 'Google TV'], variants: [] },
  { name: 'Croma 75-inch QLED TV', slug: 'croma-75-inch-qled-tv', description: 'Vibrant 4K Google TV with Dolby Atmos.', price: 99990, category: 'Televisions', brand: 'Croma', imageUrls: ['/images/tvs/croma-qled-75.jpg'], stock: 25, keyFeatures: ['QLED 4K', 'Dolby Atmos', 'Google TV'], variants: [] },
  { name: 'Croma 43-inch 4K LED', slug: 'croma-43-4k-led', description: 'Compact 4K TV with HDR and smart features.', price: 25990, category: 'Televisions', brand: 'Croma', imageUrls: ['/images/tvs/croma-led-43.jpg'], stock: 30, keyFeatures: ['4K', 'HDR10', 'Bezel-less'], variants: [] },
  { name: 'Samsung 43-inch The Frame', slug: 'samsung-43-the-frame', description: 'Lifestyle TV that looks like art when not in use.', price: 72990, category: 'Televisions', brand: 'Samsung', imageUrls: ['/images/tvs/samsung-frame.jpg'], stock: 12, keyFeatures: ['QLED 4K', 'Art Mode', 'Slim Fit Wall Mount'], variants: [] },
  { name: 'LG 32-inch HD Smart TV', slug: 'lg-32-hd-smart-tv', description: 'Affordable smart TV for bedrooms and kitchens.', price: 15990, category: 'Televisions', brand: 'LG', imageUrls: ['/images/tvs/lg-hd-32.jpg'], stock: 40, keyFeatures: ['HD Ready', 'webOS', 'AI Sound'], variants: [] },
  { name: 'Sony 75-inch Mini LED', slug: 'sony-75-mini-led', description: 'High brightness Mini LED with XR Triluminos Pro.', price: 279990, category: 'Televisions', brand: 'Sony', imageUrls: ['/images/tvs/sony-mini-led.jpg'], stock: 6, keyFeatures: ['Mini LED', 'XR Contrast Booster', 'Dolby Vision'], variants: [] },

  // Headphones (11)
  { name: 'Bose QuietComfort Ultra', slug: 'bose-quietcomfort-ultra', description: 'Breakthrough noise cancellation with immersive audio.', price: 35900, category: 'Headphones', brand: 'Bose', imageUrls: ['/images/headphones/bose-qc-ultra.jpg'], stock: 50, keyFeatures: ['ANC', 'Immersive Audio', '24h battery'], variants: [] },
  { name: 'Sony WH-1000XM5', slug: 'sony-wh-1000xm5', description: 'Industry-leading noise cancelling with superb comfort.', price: 29990, category: 'Headphones', brand: 'Sony', imageUrls: ['/images/headphones/sony-xm5.jpg'], stock: 40, keyFeatures: ['ANC', 'LDAC', '30h battery'], variants: [] },
  { name: 'JBL Tune 770NC', slug: 'jbl-tune-770nc', description: 'Punchy bass headphones with active noise cancelling.', price: 7999, category: 'Headphones', brand: 'JBL', imageUrls: ['/images/headphones/jbl-770nc.jpg'], stock: 110, keyFeatures: ['ANC', 'Pure Bass', '70h battery'], variants: [] },
  { name: 'Apple AirPods Max', slug: 'apple-airpods-max', description: 'High-fidelity audio, Active Noise Cancellation, and spatial audio.', price: 59900, category: 'Headphones', brand: 'Apple', imageUrls: ['/images/headphones/airpods-max.jpg'], stock: 25, keyFeatures: ['ANC', 'Spatial Audio', 'Digital Crown'], variants: [] },
  { name: 'Bose SoundLink Flex', slug: 'bose-soundlink-flex-headphones', description: 'Portable audio with rugged design and great sound.', price: 16900, category: 'Headphones', brand: 'Bose', imageUrls: ['/images/headphones/bose-flex.jpg'], stock: 60, keyFeatures: ['Bluetooth 5.3', 'IP67', '12h battery'], variants: [] },
  { name: 'Sony WF-1000XM5', slug: 'sony-wf-1000xm5', description: 'Flagship TWS earbuds with excellent ANC.', price: 24990, category: 'Headphones', brand: 'Sony', imageUrls: ['/images/headphones/sony-wf-xm5.jpg'], stock: 70, keyFeatures: ['ANC', 'Hi-Res Audio', 'Multipoint'], variants: [] },
  { name: 'JBL Wave Buds', slug: 'jbl-wave-buds', description: 'Comfortable, water-resistant earbuds for daily use.', price: 2999, category: 'Headphones', brand: 'JBL', imageUrls: ['/images/headphones/jbl-wave.jpg'], stock: 130, keyFeatures: ['IP54', 'Deep bass', 'TalkThru'], variants: [] },
  { name: 'Apple AirPods Pro 3', slug: 'airpods-pro-3', description: 'ANC with Transparency mode and personalized spatial audio.', price: 25900, category: 'Headphones', brand: 'Apple', imageUrls: ['/images/headphones/airpods-pro.jpg'], stock: 90, keyFeatures: ['ANC', 'Spatial Audio', 'MagSafe'], variants: [] },
  { name: 'Sony INZONE H9', slug: 'sony-inzone-h9', description: 'Gaming headset with 360 Spatial Sound and ANC.', price: 27990, category: 'Headphones', brand: 'Sony', imageUrls: ['/images/headphones/sony-inzone-h9.jpg'], stock: 25, keyFeatures: ['ANC', '2.4GHz wireless', '360 Spatial'], variants: [] },
  { name: 'Bose QuietComfort Earbuds II', slug: 'bose-qc-earbuds-ii', description: 'Excellent ANC earbuds with personalized fit.', price: 24990, category: 'Headphones', brand: 'Bose', imageUrls: ['/images/headphones/bose-qc-earbuds.jpg'], stock: 45, keyFeatures: ['ANC', 'Transparency', 'IPX4'], variants: [] },
  { name: 'JBL Live Pro 2', slug: 'jbl-live-pro-2', description: 'Comfortable buds with strong ANC and good call quality.', price: 9999, category: 'Headphones', brand: 'JBL', imageUrls: ['/images/headphones/jbl-live-pro.jpg'], stock: 60, keyFeatures: ['ANC', '6 mics', 'Qi charging'], variants: [] },

  // Refrigerators (11)
  { name: 'Samsung 236L Double Door', slug: 'samsung-236l-double-door', description: 'Frost-free with Digital Inverter for efficient cooling.', price: 25990, category: 'Refrigerators', brand: 'Samsung', imageUrls: ['/images/refrigerators/samsung-236l.jpg'], stock: 40, keyFeatures: ['236L', '2 Star', 'Digital Inverter'], variants: [] },
  { name: 'Samsung 322L Convertible', slug: 'samsung-322l-convertible', description: 'Convertible freezer with Power Cool technology.', price: 38990, category: 'Refrigerators', brand: 'Samsung', imageUrls: ['/images/refrigerators/samsung-322l.jpg'], stock: 25, keyFeatures: ['Convertible', '3 Star', 'Toughened glass'], variants: [] },
  { name: 'LG 260L Smart Inverter', slug: 'lg-260l-smart-inverter', description: 'Energy efficient and quiet operation with smart inverter.', price: 27990, category: 'Refrigerators', brand: 'LG', imageUrls: ['/images/refrigerators/lg-260l.jpg'], stock: 35, keyFeatures: ['260L', 'Smart Inverter', 'Moist balance crisper'], variants: [] },
  { name: 'LG 360L DoorCooling+', slug: 'lg-360l-doorcooling-plus', description: 'DoorCooling+ for uniform cooling and faster temperature control.', price: 46990, category: 'Refrigerators', brand: 'LG', imageUrls: ['/images/refrigerators/lg-360l.jpg'], stock: 20, keyFeatures: ['360L', 'DoorCooling+', '3 Star'], variants: [] },
  { name: 'Whirlpool 240L NeoFresh', slug: 'whirlpool-240l-neofresh', description: 'Fresh flow air tower and MicroBlock technology.', price: 23990, category: 'Refrigerators', brand: 'Whirlpool', imageUrls: ['/images/refrigerators/whirlpool-240l.jpg'], stock: 45, keyFeatures: ['240L', '3 Star', 'IntelliSense'], variants: [] },
  { name: 'Whirlpool 292L Intellisense', slug: 'whirlpool-292l-intellisense', description: 'Adaptive intelligence for consistent cooling.', price: 31990, category: 'Refrigerators', brand: 'Whirlpool', imageUrls: ['/images/refrigerators/whirlpool-292l.jpg'], stock: 28, keyFeatures: ['292L', 'IntelliSense', 'Freshonizer'], variants: [] },
  { name: 'Samsung 415L Side-by-Side', slug: 'samsung-415l-side-by-side', description: 'SpaceMax side-by-side design with power cool.', price: 69990, category: 'Refrigerators', brand: 'Samsung', imageUrls: ['/images/refrigerators/samsung-sbs.jpg'], stock: 12, keyFeatures: ['415L', 'Side-by-Side', 'Digital Inverter'], variants: [] },
  { name: 'LG 423L Frost Free', slug: 'lg-423l-frost-free', description: 'Door cooling with deodorizer for freshness.', price: 72990, category: 'Refrigerators', brand: 'LG', imageUrls: ['/images/refrigerators/lg-423l.jpg'], stock: 10, keyFeatures: ['423L', 'Door Cooling', 'Hygiene Fresh'], variants: [] },
  { name: 'Whirlpool 265L Protton', slug: 'whirlpool-265l-protton', description: '3-door Protton with moisture retention technology.', price: 32990, category: 'Refrigerators', brand: 'Whirlpool', imageUrls: ['/images/refrigerators/whirlpool-protton.jpg'], stock: 18, keyFeatures: ['265L', '3 Door', 'Active fresh zone'], variants: [] },
  { name: 'Samsung 198L Single Door', slug: 'samsung-198l-single-door', description: 'Base stand drawer and toughened glass shelves.', price: 16490, category: 'Refrigerators', brand: 'Samsung', imageUrls: ['/images/refrigerators/samsung-sd.jpg'], stock: 50, keyFeatures: ['198L', 'Base stand', 'Direct cool'], variants: [] },
  { name: 'LG 215L Single Door', slug: 'lg-215l-single-door', description: 'Smart inverter compressor and stabilizer free operation.', price: 18490, category: 'Refrigerators', brand: 'LG', imageUrls: ['/images/refrigerators/lg-sd.jpg'], stock: 46, keyFeatures: ['215L', 'Smart inverter', 'Base stand drawer'], variants: [] },
  
  // ACs (11)
  { name: 'Voltas 1.5 Ton 5 Star Inverter Split AC', slug: 'voltas-1-5t-5s-inverter-split', description: 'High energy efficiency with variable speed compressor.', price: 40990, category: 'ACs', brand: 'Voltas', imageUrls: ['/images/acs/voltas-1.5t.jpg'], stock: 30, keyFeatures: ['1.5 Ton', 'Inverter', 'Copper condenser'], variants: [] },
  { name: 'Voltas 1 Ton 3 Star Window AC', slug: 'voltas-1t-3s-window', description: 'Compact window AC with turbo cool.', price: 23990, category: 'ACs', brand: 'Voltas', imageUrls: ['/images/acs/voltas-1t-window.jpg'], stock: 40, keyFeatures: ['1 Ton', 'Window AC', 'Turbo cool'], variants: [] },
  { name: 'LG 1.5 Ton 5 Star AI Dual Inverter', slug: 'lg-1-5t-5s-ai-dual-inverter', description: 'AI dual inverter with super convertible 6-in-1 cooling.', price: 46990, category: 'ACs', brand: 'LG', imageUrls: ['/images/acs/lg-1.5t.jpg'], stock: 28, keyFeatures: ['AI Dual Inverter', '6-in-1 cooling', 'HD filter'], variants: [] },
  { name: 'LG 1 Ton 4 Star Inverter Split', slug: 'lg-1t-4s-inverter-split', description: 'Efficient cooling with ocean black protection.', price: 35990, category: 'ACs', brand: 'LG', imageUrls: ['/images/acs/lg-1t.jpg'], stock: 33, keyFeatures: ['1 Ton', 'Inverter', 'Ocean black protection'], variants: [] },
  { name: 'Daikin 1.5 Ton 5 Star Inverter', slug: 'daikin-1-5t-5s-inverter', description: 'Power chill operation with Econo mode.', price: 48990, category: 'ACs', brand: 'Daikin', imageUrls: ['/images/acs/daikin-1.5t.jpg'], stock: 22, keyFeatures: ['Power chill', 'PM2.5 filter', 'Stabilizer inside'], variants: [] },
  { name: 'Daikin 1 Ton 3 Star Split AC', slug: 'daikin-1t-3s-split', description: 'Reliable performance with quiet operation.', price: 31990, category: 'ACs', brand: 'Daikin', imageUrls: ['/images/acs/daikin-1t.jpg'], stock: 30, keyFeatures: ['1 Ton', 'Coanda airflow', 'Quiet mode'], variants: [] },
  { name: 'Voltas 1.5 Ton 3 Star Inverter', slug: 'voltas-1-5t-3s-inverter', description: 'Balanced cooling and efficiency.', price: 34990, category: 'ACs', brand: 'Voltas', imageUrls: ['/images/acs/voltas-1.5t-3s.jpg'], stock: 38, keyFeatures: ['1.5 Ton', 'Inverter', 'Anti-dust filter'], variants: [] },
  { name: 'LG 2 Ton 3 Star Split AC', slug: 'lg-2t-3s-split', description: 'Powerful cooling for large rooms.', price: 55990, category: 'ACs', brand: 'LG', imageUrls: ['/images/acs/lg-2t.jpg'], stock: 12, keyFeatures: ['2 Ton', 'Super convertible', 'HD filter'], variants: [] },
  { name: 'Daikin 1.8 Ton 5 Star Inverter', slug: 'daikin-1-8t-5s-inverter', description: 'Energy efficient with triple display.', price: 61990, category: 'ACs', brand: 'Daikin', imageUrls: ['/images/acs/daikin-1.8t.jpg'], stock: 10, keyFeatures: ['1.8 Ton', 'Econo mode', 'Stabilizer free'], variants: [] },
  { name: 'Voltas 2 Ton 3 Star Window AC', slug: 'voltas-2t-3s-window', description: 'Heavy-duty window AC for fast cooling.', price: 34990, category: 'ACs', brand: 'Voltas', imageUrls: ['/images/acs/voltas-2t-window.jpg'], stock: 15, keyFeatures: ['2 Ton', 'Window', 'Copper condenser'], variants: [] },
  { name: 'LG 1.5 Ton 5 Star Hot & Cold', slug: 'lg-1-5t-5s-hot-and-cold', description: 'Cooling in summer and heating in winter.', price: 58990, category: 'ACs', brand: 'LG', imageUrls: ['/images/acs/lg-hot-cold.jpg'], stock: 8, keyFeatures: ['Hot & Cold', 'AI dual inverter', 'Low gas detection'], variants: [] },

  // Speakers (11)
  { name: 'Bose SoundLink Flex Portable', slug: 'bose-soundlink-flex-portable', description: 'Rugged portable speaker with high-fidelity audio.', price: 16900, category: 'Speakers', brand: 'Bose', imageUrls: ['/images/speakers/bose-flex.jpg'], stock: 75, keyFeatures: ['Bluetooth 5.3', 'IP67', '12h battery'], variants: [] },
  { name: 'Bose Smart Soundbar 600', slug: 'bose-smart-soundbar-600', description: 'Dolby Atmos soundbar with voice assistants built-in.', price: 55990, category: 'Speakers', brand: 'Bose', imageUrls: ['/images/speakers/bose-sb600.jpg'], stock: 18, keyFeatures: ['Dolby Atmos', 'Wi-Fi & BT', 'Voice assistants'], variants: [] },
  { name: 'JBL Flip 6', slug: 'jbl-flip-6', description: 'Portable waterproof speaker with bold sound.', price: 11999, category: 'Speakers', brand: 'JBL', imageUrls: ['/images/speakers/jbl-flip6.jpg'], stock: 90, keyFeatures: ['IP67', '12h battery', 'PartyBoost'], variants: [] },
  { name: 'JBL PartyBox 110', slug: 'jbl-partybox-110', description: 'Powerful party speaker with dynamic lights.', price: 29999, category: 'Speakers', brand: 'JBL', imageUrls: ['/images/speakers/jbl-partybox.jpg'], stock: 20, keyFeatures: ['160W sound', 'Mic & guitar input', 'IPX4'], variants: [] },
  { name: 'Samsung Q-Series Soundbar', slug: 'samsung-q-series-soundbar', description: 'Immersive soundbar with Q-Symphony.', price: 45990, category: 'Speakers', brand: 'Samsung', imageUrls: ['/images/speakers/samsung-soundbar.jpg'], stock: 14, keyFeatures: ['Dolby Atmos', 'Q-Symphony', 'Wireless sub'], variants: [] },
  { name: 'Samsung Sound Tower', slug: 'samsung-sound-tower', description: 'Party speaker with bi-directional sound.', price: 22990, category: 'Speakers', brand: 'Samsung', imageUrls: ['/images/speakers/samsung-tower.jpg'], stock: 22, keyFeatures: ['Bi-directional', 'Karaoke', 'Bass boost'], variants: [] },
  { name: 'Sony SRS-XE300', slug: 'sony-srs-xe300', description: 'Portable speaker with line-shape diffuser.', price: 14990, category: 'Speakers', brand: 'Sony', imageUrls: ['/images/speakers/sony-xe300.jpg'], stock: 40, keyFeatures: ['Water/dust resistant', '24h battery', 'Fast charge'], variants: [] },
  { name: 'Sony HT-S2000', slug: 'sony-ht-s2000', description: 'Dolby Atmos/DTS:X compact soundbar.', price: 29990, category: 'Speakers', brand: 'Sony', imageUrls: ['/images/speakers/sony-hts2000.jpg'], stock: 16, keyFeatures: ['Dolby Atmos', '360 Spatial', 'Virtual surround'], variants: [] },
  { name: 'Bose Home Speaker 500', slug: 'bose-home-speaker-500', description: 'Room-filling stereo sound from a single speaker.', price: 35900, category: 'Speakers', brand: 'Bose', imageUrls: ['/images/speakers/bose-home500.jpg'], stock: 24, keyFeatures: ['Wi-Fi & BT', 'Voice assistants', 'Color display'], variants: [] },
  { name: 'JBL Bar 500', slug: 'jbl-bar-500', description: '5.1-channel soundbar with MultiBeam technology.', price: 35999, category: 'Speakers', brand: 'JBL', imageUrls: ['/images/speakers/jbl-bar500.jpg'], stock: 18, keyFeatures: ['Dolby Atmos', 'MultiBeam', 'PureVoice'], variants: [] },
  { name: 'Sony HT-A3000', slug: 'sony-ht-a3000', description: '3.1ch soundbar with virtual surround and deep bass.', price: 59990, category: 'Speakers', brand: 'Sony', imageUrls: ['/images/speakers/sony-hta3000.jpg'], stock: 10, keyFeatures: ['360 Spatial', 'Dolby Atmos', 'Wi-Fi'], variants: [] },
  
  // Cameras (11)
  { name: 'Nikon Z6 III', slug: 'nikon-z6-iii', description: 'Hybrid mirrorless with fast AF and low-light performance.', price: 189990, category: 'Cameras', brand: 'Nikon', imageUrls: ['/images/cameras/nikon-z6.jpg'], stock: 12, keyFeatures: ['24.5MP', '6K video', 'IBIS'], variants: [] },
  { name: 'Nikon Z8', slug: 'nikon-z8', description: 'Professional mirrorless with powerful video features.', price: 349990, category: 'Cameras', brand: 'Nikon', imageUrls: ['/images/cameras/nikon-z8.jpg'], stock: 6, keyFeatures: ['45.7MP', '8K video', 'Stacked sensor'], variants: [] },
  { name: 'Canon EOS R6 Mark II', slug: 'canon-eos-r6-mark-ii', description: 'Versatile hybrid camera with excellent AF.', price: 229990, category: 'Cameras', brand: 'Canon', imageUrls: ['/images/cameras/canon-r6.jpg'], stock: 10, keyFeatures: ['24.2MP', '4K60p', 'IBIS'], variants: [] },
  { name: 'Canon EOS R7', slug: 'canon-eos-r7', description: 'APS-C mirrorless with high speed burst.', price: 149990, category: 'Cameras', brand: 'Canon', imageUrls: ['/images/cameras/canon-r7.jpg'], stock: 14, keyFeatures: ['32.5MP', 'IBIS', '4K60p'], variants: [] },
  { name: 'Sony Alpha A7 IV', slug: 'sony-alpha-a7-iv', description: 'All-round full-frame with advanced AF and color science.', price: 224990, category: 'Cameras', brand: 'Sony', imageUrls: ['/images/cameras/sony-a7iv.jpg'], stock: 12, keyFeatures: ['33MP', '4K60p', 'Real-time AF'], variants: [] },
  { name: 'Sony ZV-E10', slug: 'sony-zv-e10', description: 'Vlogging mirrorless with interchangeable lenses.', price: 69990, category: 'Cameras', brand: 'Sony', imageUrls: ['/images/cameras/sony-zve10.jpg'], stock: 20, keyFeatures: ['APS-C', 'Product showcase', 'Directional mic'], variants: [] },
  { name: 'Nikon Z50', slug: 'nikon-z50', description: 'Compact APS-C camera with strong ergonomics.', price: 67990, category: 'Cameras', brand: 'Nikon', imageUrls: ['/images/cameras/nikon-z50.jpg'], stock: 18, keyFeatures: ['20.9MP', 'Eye-detect AF', '4K'], variants: [] },
  { name: 'Canon EOS R50', slug: 'canon-eos-r50', description: 'Lightweight APS-C with user-friendly controls.', price: 69990, category: 'Cameras', brand: 'Canon', imageUrls: ['/images/cameras/canon-r50.jpg'], stock: 22, keyFeatures: ['24.2MP', 'Dual Pixel AF II', '4K30p'], variants: [] },
  { name: 'Sony Alpha A7C II', slug: 'sony-alpha-a7c-ii', description: 'Compact full-frame with strong tracking AF.', price: 214990, category: 'Cameras', brand: 'Sony', imageUrls: ['/images/cameras/sony-a7cii.jpg'], stock: 9, keyFeatures: ['33MP', '5-axis IBIS', '4K60p'], variants: [] },
  { name: 'Canon EOS R10', slug: 'canon-eos-r10', description: 'Entry APS-C mirrorless with advanced AF modes.', price: 84990, category: 'Cameras', brand: 'Canon', imageUrls: ['/images/cameras/canon-r10.jpg'], stock: 26, keyFeatures: ['24.2MP', '4K30p', 'OVF Assist'], variants: [] },
  { name: 'Nikon Z30', slug: 'nikon-z30', description: 'Vlogger-friendly with compact design.', price: 59990, category: 'Cameras', brand: 'Nikon', imageUrls: ['/images/cameras/nikon-z30.jpg'], stock: 24, keyFeatures: ['20.9MP', '4K30p', 'Vari-angle LCD'], variants: [] },
  
  // Smartwatches (3)
  { name: 'Apple Watch Ultra 3', slug: 'watch-ultra-3', description: 'Rugged titanium design with brightest display and advanced fitness features.', price: 89900, category: 'Smartwatches', brand: 'Apple', imageUrls: ['/images/watch-pro.jpg'], stock: 20, keyFeatures: ['Titanium', 'Up to 36h battery', 'Depth gauge'], variants: [] },
  { name: 'Apple Watch Series 11', slug: 'watch-series-11', description: 'Powerful health and fitness companion with advanced safety features.', price: 45900, category: 'Smartwatches', brand: 'Apple', imageUrls: ['/images/series-11.jpg'], stock: 40, keyFeatures: ['Always‑On Retina', 'Crash Detection', 'Cycle tracking'], variants: [] },
  { name: 'Apple Watch SE (3rd gen)', slug: 'watch-se-3', description: 'All the essentials to help you be motivated and active.', price: 29900, category: 'Smartwatches', brand: 'Apple', imageUrls: ['/images/watch-se.jpg'], stock: 50, keyFeatures: ['Fall Detection', 'Water resistant', 'Family Setup'], variants: [] },

  // Gaming Consoles (1)
  { name: 'Sony PlayStation 5 Slim', slug: 'sony-playstation-5-slim', description: 'Next-gen gaming with ultra-high speed SSD in a slimmer design.', price: 49990, category: 'Gaming Consoles', brand: 'Sony', imageUrls: ['/images/sony-ps.jpg'], stock: 15, keyFeatures: ['4K gaming', 'Haptic feedback', 'Tempest 3D AudioTech'], variants: [] },

  // Additional featured products for homepage (2)
  { name: 'Croma 236L Frost Free Refrigerator', slug: 'croma-236l-refrigerator', description: 'Compact 236L refrigerator with efficient cooling and toughened glass shelves.', price: 21990, category: 'Refrigerators', brand: 'Croma', imageUrls: ['/images/croma-fridge.jpg'], stock: 25, keyFeatures: ['236L', 'Frost Free', 'Toughened shelves'], variants: [] },
  { name: 'OnePlus 13s 5G', slug: 'oneplus-13s-5g', description: 'Refined flagship with high-refresh ProXDR display and fast charging.', price: 57999, category: 'Mobiles', brand: 'OnePlus', imageUrls: ['/images/mobiles/oneplus-13.jpg'], stock: 35, keyFeatures: ['120Hz', 'Fast charging', 'Hasselblad tuning'], variants: [] },
];

const importData = async () => {
  try {
    await connectDB();
    console.log('Database connected, deleting old products...');
    await Product.deleteMany();
    console.log('Old products deleted, inserting new ones...');
    await Product.insertMany(products);
    console.log('✅ Products seeded successfully!');
  } catch (error) {
    console.error('❌ An error occurred during the seeding process:');
    console.error(error);
  } finally {
    console.log('Closing database connection...');
    await mongoose.connection.close();
    console.log('Connection closed. Script finished.');
  }
};

importData();